### PR TITLE
Add attributes in Future Solution

### PR DESCRIPTION
**Pull request by whhxp**

### CODE REVIEW

**Comment by dhadka** [comment]
Thanks for this contribution!  I have two suggestions:

1. I believe `SerializationUtils.clone` can be removed.  Since the "future solution" is not accessed anywhere else, we can simply copy the attributes and avoid cloning.

2. Please override the *Attribute methods (getAttribute, hasAttribute, getAttributes, etc.).  Similar to the other overridden methods, it should call update() first.  This way, if the program tries to read an attribute, it will wait until the distributed evaluation completes.

**Comment by whhxp** [comment]
OK, I will do that.

**Comment by dhadka** [comment]
I've gone ahead and applied this change to master (including my suggestions).  Closing the PR.

**Comment by dhadka** [comment]
For reference, this is the commit: https://github.com/MOEAFramework/MOEAFramework/commit/7c7acaf5bd5eb249aa7c3e88c6acaafca1e97307

**Pull request closed without merging**
